### ISSUE TITLE
Powered area highlight performance is not up to par

### ISSUE THREAD

**Issue by caryoscelus** [spirulence/power-department-ld38#37]
When the network becomes very big, powered area highlighting becomes quite slow.

**Comment by spirulence** [comment]
`...highlight performance is not up to par` <- was that an in-joke? 👍 

This problem also applies to line placement when the lines become large - I haven't profiled, but I think the fix is likely making lines and powered area highlights their own `Phaser.Group` objects containing simple `Phaser.Sprite`s. Every time a tilemap is altered, Phaser does a lot of recalculating and re-rendering that's ultimately just redone when the next tile is altered...

**Comment by caryoscelus** [comment]
>was that an in-joke?

Yep.

I should perhaps also mention that general load seems too big: the game constantly eats about one whole core (on my firefox), even when nothing happens. This might be not related to your code, though.
